name = "html_components"

version = "0.2.0"

description = "Generate HTML (or XML) from simple gleam functions"
licences = ["MIT"]
repository = { type = "github", user = "andre-dasilva", repo = "html_components" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
